# Generated by Django 3.2.9 on 2021-11-22 16:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('klikaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('priority', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='table',
            name='location',
        ),
        migrations.RemoveField(
            model_name='table',
            name='sub_location',
        ),
        migrations.AddField(
            model_name='business',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='reservations',
            name='priority',
            field=models.CharField(blank=True, choices=[(1, 'Low'), (2, 'Regular'), (3, 'High')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='table',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='table_id',
        ),
        migrations.AddField(
            model_name='reservations',
            name='table_id',
            field=models.ManyToManyField(to='klikaapp.Table'),
        ),
        migrations.AddField(
            model_name='table',
            name='location_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='klikaapp.location'),
        ),
    ]
