# Generated by Django 3.2.9 on 2021-11-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klikaapp', '0003_auto_20211122_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Low'), (2, 'Regular'), (3, 'High')], null=True),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='table_id',
            field=models.ManyToManyField(to='klikaapp.Table'),
        ),
    ]
