# Generated by Django 3.2.9 on 2021-11-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klikaapp', '0004_auto_20211122_1849'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='address_id',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='reservations',
            old_name='business_id',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='reservations',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='reservations',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='business_id',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='location_id',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='table_id',
            field=models.ManyToManyField(to='klikaapp.Table'),
        ),
    ]
