# Generated by Django 3.2.9 on 2021-11-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klikaapp', '0005_auto_20211122_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='table_id',
            new_name='table',
        ),
        migrations.AlterField(
            model_name='reservations',
            name='table',
            field=models.ManyToManyField(to='klikaapp.Table'),
        ),
    ]
