# Generated by Django 3.2.9 on 2021-11-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klikaapp', '0008_auto_20211127_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='table',
            field=models.ManyToManyField(to='klikaapp.Table'),
        ),
    ]
