# Generated by Django 3.2.9 on 2021-11-27 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_address_id_profile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
